import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import FilterNavbar from "@/components/layout/FilterNavbar";
import SearchNavbar from "@/components/layout/SearchNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-8  py-2 bg-primary text-primary-foreground">
         <div className="max-w-screen-2xl mx-auto">
           <Navbar />
          <FilterNavbar />
          <SearchNavbar/>
         </div>
        </header>
       <main className="max-w-screen-2xl mx-auto">
         {children}
       </main>
      </body>
    </html>
  );
}
